# Params for TFMaT model
description: "TFMaT validate_only parameters"

model:
    sequence_length: 1000
    motif_size: 6000
    motif_length_max: 35
    num_layers: 12
    num_heads: 12
    name: 'TFMaT_test'
    hidden_size: 768
    mlp_dim: 3072
    classes: 1000
    dropout: 0.1
    activation: 'sigmoid'
    representation_size: 768
    motif_embedding_trainable: False
    lr: 0.001

runconfig:
    max_steps: 10000000
    save_summary_steps: 5000
    save_checkpoints_steps: 100000
    keep_checkpoint_max: 2
    model_dir: 'model_dir'
    cs_ip:
    mode: 'train'
